FORMAT: 1A

# MEASUREMENT

An API for logging humidity & temperature measurements

## Devices Collection [/device]

### List All Devices [GET]

+ Request (application/json)
    + Headers

            Authorization: Bearer rEWnnWOlGlFc0O6YEixmXsmyIkxblaKUTUnLCj1HAeHpBqVfzEdPUEmkKZMf

+ Response 200 (application/json)
    + Attributes

            {
                "data": (array[Device]),
                "meta": {
                    "pagination": {
                        "total": 49,
                        "count": 15,
                        "per_page": 15,
                        "current_page": 1,
                        "total_pages": 4,
                        "links": {
                            "next": "http://measurement.dev:2015/v1/device?page=2"
                        }
                    }
                }
            }

### Create a Device [POST]

+ Request (application/json)
    + Headers

            Authorization: Bearer rEWnnWOlGlFc0O6YEixmXsmyIkxblaKUTUnLCj1HAeHpBqVfzEdPUEmkKZMf
    + Attributes (Device Create)

+ Response 201 (application/json)
    + Headers

            Location: /device/1
    + Attributes

            - data (Device Full)

### Update a Device [PUT /device/{id}]

+ Parameters
    + id: 1 (number, required) - ID of a device.

+ Request (application/json)
    + Headers

            Authorization: Bearer rEWnnWOlGlFc0O6YEixmXsmyIkxblaKUTUnLCj1HAeHpBqVfzEdPUEmkKZMf
    + Attributes (Device Update)

+ Response 200 (application/json)
    + Attributes

        - data (Device Full)

### Delete a Device [DELETE /device/{id}]

+ Parameters
    + id: 2 (number, required) - ID of a device.

+ Request (application/json)
    + Headers

            Authorization: Bearer rEWnnWOlGlFc0O6YEixmXsmyIkxblaKUTUnLCj1HAeHpBqVfzEdPUEmkKZMf

+ Response 200 (application/json)
    + Attributes

            - data (Device Full)

## Data Structures

### Device Update (object)
- Include Device Create
- mac_address: `DA:A0:FK:2C:1E:74` (string)

### Device Create (object)

- name: `Kitchen` (string) - Name of a device
- mac_address: `DA:A0:ZX:2C:1E:74` (string) - MAC address of a device
- description: `Numquam laboriosam et et consequatur tempora error blanditiis` (string) - Description of a device

### Device Full (object)

- id: `1` (number, required) - ID of a device
- Include Device Create
- created_at: `2016-08-04T11:01:52+0000` (string) - ISO8601 datetime where a device is created
- updated_at: `2016-08-04T11:01:52+0000` (string) - ISO8601 datetime where a device is updated


